### ISSUE TITLE
Improve the design and fix mobile/tablet view

### ISSUE THREAD

**Issue by Asif-Tanvir-2006** [Asif-Tanvir-2006/leaderboard_winterofcode#1]
# Improve UI Design: Make Leaderboard Responsive and Aesthetically Pleasing

## 📝 Objective
Enhance the visual appearance of the leaderboard and ensure it is responsive across all screen sizes.

---

## 🎯 Tasks
1. Adjust the font size and table dimensions based on screen sizes using media queries.
2. Improve the overall design to make it visually appealing (e.g., colors, borders, spacing).
3. Ensure the leaderboard is fully responsive and looks good on:
   - Mobile devices
   - Tablets
   - Desktop screens.

---

## 💡 Suggestions
- Use CSS media queries to handle different breakpoints.
- Add padding, margins, or borders to improve readability.
- Choose visually pleasing fonts and colors.
- Test the design on various devices to ensure consistency.

---

## 📋 Skills Required
- CSS (including media queries).
- Basic design principles.

---

## 📂 File(s) to Update
- `style.css` (or wherever the CSS is defined).

---

## ✅ Acceptance Criteria
-  Font size and table layout adapt properly to different screen sizes.
-  Improved design looks polished and professional.
-  No horizontal scrolling on mobile devices.

---

## 🔖 Labels
`enhancement`, `good first issue`, `UI/UX`, `CSS`

**Comment by Sneha-Das1** [comment]
Hello, kindly assign me this issue.

**Comment by Asif-Tanvir-2006** [comment]
Hello @Sneha-Das1, I'm assigning this issue to you
