### ISSUE TITLE
Fix pagination

### ISSUE THREAD

**Issue by Asif-Tanvir-2006** [Asif-Tanvir-2006/leaderboard_winterofcode#3]
# Enhance Pagination and Display Total Entries

## 📝 Objective
Improve the pagination feature for the leaderboard table and display the total number of entries for better user experience.

---

## 🎯 Tasks
1. Enhance the current pagination to allow users to:
   - Navigate between pages easily.
   - Jump to the first/last page.
   - Specify number of entries to display per page in the table (e.g- 10, 15, 20 entries per page)
2. Display the **total number of entries** in the leaderboard above or below the table.
3. Ensure that the table updates dynamically as users navigate through pages or change the number of entries per page.

---

## 💡 Suggestions
- For the total number of entries, calculate and display it dynamically based on the data.
- Add controls for navigation, such as:
  - **Previous** and **Next** buttons.
  - **Page Numbers** for direct access.
  - A dropdown to select entries per page (e.g., 10, 20, 50).
- Maintain consistent UI/UX design with the rest of the leaderboard.

---

## 📋 Skills Required
- JavaScript (Logic)
- HTML (for adding new elements like buttons, dropdown menu)
- CSS (styling the newly added elements)

---

## 📂 File(s) to Update
- `script.js` (or equivalent for handling pagination logic).
- `index.html` (if new elements like dropdowns or buttons are added).
- `style.css` (for styling the pagination and entry count).

---

## ✅ Acceptance Criteria
- Pagination works smoothly with options to navigate pages and adjust the number of entries per page.
-  Total number of entries is displayed dynamically above or below the table.
- Pagination and entry count are responsive across different devices.

---

## 🔖 Labels
`enhancement`, `good first issue`, `JavaScript`, `Pagination`, `UI/UX`

**Comment by servoserv** [comment]
plese assign this issue to me so that i an work on this

**Comment by servoserv** [comment]
Recently i completed all the issues assigned to me so can this issue be now assigned to me
i want to work on this although i worked on this issue and completed in my local machine

**Comment by Asif-Tanvir-2006** [comment]
OKay @servoserv
