### ISSUE TITLE
Fix duplicate entry 

### ISSUE THREAD

**Issue by Asif-Tanvir-2006** [Asif-Tanvir-2006/leaderboard_winterofcode#4]
# Skip the First Entry of the Table

## 📝 Objective
Modify the leaderboard table so that the first entry is skipped (e.g., not displayed in the list).

---

## 🎯 Tasks
1. Add logic to exclude the first entry of the leaderboard table when displaying the data.
2. Ensure this change applies only on the first page.
![image](https://github.com/user-attachments/assets/45a9e1ad-1283-4e69-a767-e258ec9c84c3)

As you can see, the name, year, easy, etc - these are repeated twice, this is what needs fixing

---

## 📂 File(s) to Update
- `script.js`
---

## ✅ Acceptance Criteria
-  The first entry of the leaderboard is not displayed in the table.

---

## 🔖 Labels
 `JavaScript`, `BUG`

**Comment by reevu1** [comment]
hi, i want to work on this issue

**Comment by Asif-Tanvir-2006** [comment]
Tell me your actual name with which u registered @reevu1 

> hi, i want to work on this issue

**Comment by Asif-Tanvir-2006** [comment]
Nvm i found your name, I am assigning this issue to you @reevu1 

> hi, i want to work on this issue

**Comment by Asif-Tanvir-2006** [comment]
PR accepted
