### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Asif-Tanvir-2006** [Asif-Tanvir-2006/leaderboard_winterofcode#7]
# ARGUABLY THE EASIEST ISSUE lol
## HOW DO I CONTRIBUTE?
-  Clone the repo and try to understand how the code wors
-  Identify the TECHSTACK
-  Brainstorm to know how things are working
-  Based on your understanding, create a documentation, that is, Improve the README File

### That's literally it

**Comment by servoserv** [comment]
hello so i want to work on this issue please assign this issue to me

**Comment by Asif-Tanvir-2006** [comment]
Okay, I am assigning this issue to u @servoserv

**Comment by Asif-Tanvir-2006** [comment]
Marking this issue as resolved and closing it
