### ISSUE TITLE
Dark/Light Mode Toggle

### ISSUE THREAD

**Issue by Asif-Tanvir-2006** [Asif-Tanvir-2006/leaderboard_winterofcode#8]
# As of right now there's only dark mode, which is not so cool

## Suggestions
- The light mode and dark mode should look good
-  You can modify the hexcodes of the current colours in use according to your wish 
-  Add a toggle button at the corner 

### Go ahead, the `style.css` is all yours!

**Comment by shantanu812** [comment]
Please assign this issue

**Comment by Asif-Tanvir-2006** [comment]
> Please assign this issue

Fine, I'm assigning this to you @shantanu812 
Also check the discord channel 'Leaderboard template' once

**Comment by Asif-Tanvir-2006** [comment]
Marking this as resolved and closing this issue
